services:
  - type: web
    name: fitness-tracker-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npx prisma db push && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fitness-tracker-db
          property: connectionString
      - key: NODE_ENV
        value: production
databases:
  - name: fitness-tracker-db
    plan: free

